<?php

/*
|--------------------------------------------------------------------------
| Sitemap URLs
|--------------------------------------------------------------------------
|
| Single source of truth for the site's public URLs. Consumed by both the
| dynamic /sitemap.xml route (App\Http\Controllers\SitemapController) and
| the sitemap:generate console command. Each entry is [path, priority,
| changefreq]. Absolute URLs are built from config('app.url') at runtime,
| so the sitemap always matches the environment it is served from.
|
*/

return [
    'urls' => [
        ['/', 1.0, 'weekly'],
        ['/about', 0.8, 'monthly'],
        ['/family-medicine', 0.9, 'monthly'],
        ['/psychiatric-care', 0.9, 'monthly'],
        ['/weight-loss', 0.9, 'monthly'],
        ['/iv-fluids', 0.8, 'monthly'],
        ['/ketamine', 0.8, 'monthly'],
        ['/contact', 0.7, 'monthly'],
        ['/insurance', 0.7, 'monthly'],
        ['/telehealth', 0.8, 'monthly'],
        ['/logan-cache-valley', 0.7, 'monthly'],
        ['/services/utah', 0.8, 'monthly'],
        ['/services/arizona', 0.8, 'monthly'],
        // Utah telehealth city pages
        ['/telehealth/utah/beaver', 0.6, 'monthly'],
        ['/telehealth/utah/blanding', 0.6, 'monthly'],
        ['/telehealth/utah/cedar-city', 0.6, 'monthly'],
        ['/telehealth/utah/dutch-john', 0.6, 'monthly'],
        ['/telehealth/utah/heber-city', 0.6, 'monthly'],
        ['/telehealth/utah/helper', 0.6, 'monthly'],
        ['/telehealth/utah/layton', 0.6, 'monthly'],
        ['/telehealth/utah/moab', 0.6, 'monthly'],
        ['/telehealth/utah/ogden', 0.6, 'monthly'],
        ['/telehealth/utah/orem', 0.6, 'monthly'],
        ['/telehealth/utah/park-city', 0.6, 'monthly'],
        ['/telehealth/utah/price', 0.6, 'monthly'],
        ['/telehealth/utah/provo', 0.6, 'monthly'],
        ['/telehealth/utah/salt-lake-city', 0.6, 'monthly'],
        ['/telehealth/utah/sandy', 0.6, 'monthly'],
        ['/telehealth/utah/spanish-fork', 0.6, 'monthly'],
        ['/telehealth/utah/st-george', 0.6, 'monthly'],
        ['/telehealth/utah/vernal', 0.6, 'monthly'],
        ['/telehealth/utah/wendover', 0.6, 'monthly'],
        // Utah telehealth city pages — Tier 1-3 rural/regional expansion
        ['/telehealth/utah/richfield', 0.6, 'monthly'],
        ['/telehealth/utah/roosevelt', 0.6, 'monthly'],
        ['/telehealth/utah/nephi', 0.6, 'monthly'],
        ['/telehealth/utah/delta', 0.6, 'monthly'],
        ['/telehealth/utah/kanab', 0.6, 'monthly'],
        ['/telehealth/utah/monticello', 0.6, 'monthly'],
        ['/telehealth/utah/ephraim', 0.6, 'monthly'],
        ['/telehealth/utah/tremonton', 0.6, 'monthly'],
        ['/telehealth/utah/tooele', 0.6, 'monthly'],
        ['/telehealth/utah/brigham-city', 0.6, 'monthly'],
        ['/telehealth/utah/fillmore', 0.6, 'monthly'],
        ['/telehealth/utah/panguitch', 0.6, 'monthly'],
        ['/telehealth/utah/gunnison', 0.6, 'monthly'],
        ['/telehealth/utah/mount-pleasant', 0.6, 'monthly'],
        ['/telehealth/utah/green-river', 0.6, 'monthly'],
        ['/telehealth/utah/castle-dale', 0.6, 'monthly'],
        ['/telehealth/utah/duchesne', 0.6, 'monthly'],
        ['/telehealth/utah/milford', 0.6, 'monthly'],
        ['/telehealth/utah/hurricane', 0.6, 'monthly'],
        ['/telehealth/utah/escalante', 0.6, 'monthly'],
        ['/telehealth/utah/loa', 0.6, 'monthly'],
        ['/telehealth/utah/garden-city', 0.6, 'monthly'],
        ['/telehealth/utah/roy', 0.6, 'monthly'],
        ['/telehealth/utah/american-fork', 0.6, 'monthly'],
        ['/telehealth/utah/murray', 0.6, 'monthly'],
        ['/telehealth/utah/west-valley-city', 0.6, 'monthly'],
        ['/telehealth/utah/coalville', 0.6, 'monthly'],
        ['/telehealth/utah/bluff', 0.6, 'monthly'],
        ['/telehealth/utah/hanksville', 0.6, 'monthly'],
        ['/telehealth/utah/parowan', 0.6, 'monthly'],
        ['/telehealth/utah/morgan', 0.6, 'monthly'],
        // Arizona telehealth city pages
        ['/telehealth/arizona/apache-junction', 0.6, 'monthly'],
        ['/telehealth/arizona/buckeye', 0.6, 'monthly'],
        ['/telehealth/arizona/casa-grande', 0.6, 'monthly'],
        ['/telehealth/arizona/flagstaff', 0.6, 'monthly'],
        ['/telehealth/arizona/goodyear', 0.6, 'monthly'],
        ['/telehealth/arizona/kingman', 0.6, 'monthly'],
        ['/telehealth/arizona/lake-havasu-city', 0.6, 'monthly'],
        ['/telehealth/arizona/maricopa', 0.6, 'monthly'],
        ['/telehealth/arizona/mesa', 0.6, 'monthly'],
        ['/telehealth/arizona/page', 0.6, 'monthly'],
        ['/telehealth/arizona/phoenix', 0.6, 'monthly'],
        ['/telehealth/arizona/prescott', 0.6, 'monthly'],
        ['/telehealth/arizona/queen-creek', 0.6, 'monthly'],
        ['/telehealth/arizona/san-tan-valley', 0.6, 'monthly'],
        ['/telehealth/arizona/scottsdale', 0.6, 'monthly'],
        ['/telehealth/arizona/sierra-vista', 0.6, 'monthly'],
        ['/telehealth/arizona/surprise', 0.6, 'monthly'],
        ['/telehealth/arizona/tempe', 0.6, 'monthly'],
        ['/telehealth/arizona/tuba-city', 0.6, 'monthly'],
        ['/telehealth/arizona/tucson', 0.6, 'monthly'],
        ['/telehealth/arizona/yuma', 0.6, 'monthly'],
        ['/services/montana', 0.8, 'monthly'],
        ['/services/iowa', 0.8, 'monthly'],
        // Montana telehealth city pages
        ['/telehealth/montana/billings', 0.6, 'monthly'],
        ['/telehealth/montana/missoula', 0.6, 'monthly'],
        ['/telehealth/montana/great-falls', 0.6, 'monthly'],
        ['/telehealth/montana/bozeman', 0.6, 'monthly'],
        ['/telehealth/montana/butte', 0.6, 'monthly'],
        ['/telehealth/montana/helena', 0.6, 'monthly'],
        ['/telehealth/montana/kalispell', 0.6, 'monthly'],
        ['/telehealth/montana/havre', 0.6, 'monthly'],
        ['/telehealth/montana/miles-city', 0.6, 'monthly'],
        ['/telehealth/montana/glendive', 0.6, 'monthly'],
        ['/telehealth/montana/lewistown', 0.6, 'monthly'],
        ['/telehealth/montana/dillon', 0.6, 'monthly'],
        ['/telehealth/montana/hamilton', 0.6, 'monthly'],
        ['/telehealth/montana/polson', 0.6, 'monthly'],
        ['/telehealth/montana/sidney', 0.6, 'monthly'],
        // Iowa telehealth city pages
        ['/telehealth/iowa/des-moines', 0.6, 'monthly'],
        ['/telehealth/iowa/cedar-rapids', 0.6, 'monthly'],
        ['/telehealth/iowa/davenport', 0.6, 'monthly'],
        ['/telehealth/iowa/sioux-city', 0.6, 'monthly'],
        ['/telehealth/iowa/iowa-city', 0.6, 'monthly'],
        ['/telehealth/iowa/waterloo', 0.6, 'monthly'],
        ['/telehealth/iowa/ames', 0.6, 'monthly'],
        ['/telehealth/iowa/council-bluffs', 0.6, 'monthly'],
        ['/telehealth/iowa/dubuque', 0.6, 'monthly'],
        ['/telehealth/iowa/mason-city', 0.6, 'monthly'],
        ['/telehealth/iowa/fort-dodge', 0.6, 'monthly'],
        ['/telehealth/iowa/marshalltown', 0.6, 'monthly'],
        ['/telehealth/iowa/ottumwa', 0.6, 'monthly'],
        ['/telehealth/iowa/burlington', 0.6, 'monthly'],
        ['/telehealth/iowa/carroll', 0.6, 'monthly'],
    ],
];
